#!/bin/sh

mkdir -p /download/rtorrent/session

if [ -f /root/.rtorrent.rc ]; then
  rm /root/.rtorrent.rc
fi

if [ -f /download/rtorrent.rc ]; then
  ln -s /download/rtorrent.rc /root/.rtorrent.rc
fi

if [ ! -f /download/httppassword ]; then
  ln -s /root/httppassword /download/httppassword
fi

rm -rf /download/rtorrent/session/rtorrent.lock

lighttpd -f /etc/lighttpd/lighttpd.conf

tmux new -s rtorrent rtorrent
